### ISSUE TITLE
Stroke settings not transferring

### ISSUE THREAD

**Issue by revereche** [folkertdev/freestyle-gpencil-exporter#5]
Using Blender 2.79b on Windows 10, HP laptop. Color is working, but thickness information doesn't transfer to the strokes whether in 3d or screen draw mode. Stroke color, thickness, and alpha all on in Extract Freestyle Settings. Base color or first vertex selected, it doesn't matter. Apart from uniformly thick black lines, it's working perfectly. I've tried Blender Render and Cycles.

Freestyle:
![zirafreestyle](https://user-images.githubusercontent.com/5614119/40904621-2d6ab6a2-6790-11e8-81d5-7a1dcae723e3.jpg)

GP:
![ziragp](https://user-images.githubusercontent.com/5614119/40904635-354f751a-6790-11e8-9e4f-c1e896d6d795.jpg)

EDIT: Color's not working again, but thickness works as long as I have the thickness up high enough, so I guess the problem is expecting too much of pre-2.8 Grease Pencil.
![ziragp2](https://user-images.githubusercontent.com/5614119/40906066-93fad9e8-6794-11e8-8eef-2deace29cf28.jpg)

**Comment by revereche** [comment]
Also, not a bug, but I think I remember that you could extract geometry as color fill? There was a video of a cake going from FreeStyle to Grease Pencil, complete with color fill... or am I remembering that wrong?

**Comment by folkertdev** [comment]
Is there any logic to when color does and doesn't work? it should at least be consistent. 
The thickness is a bit tricky because GP doesn't use pixels/units but a "pressure" value, so the thicknesses of the strokes are correct relative to each other, but may be a bit different from the freestyle render. 

The colored fills are part of the freestyle-svg-exporter, I think that at the time I wrote this fills weren't possible with grease pencil. Might have a go at it in 2.8/during the summer though, there have been a lot of improvements to the GP since.

**Comment by revereche** [comment]
Ahh, okay, thanks! Haven't noticed a pattern yet, I only noticed color was working at all in the one image after I posted it. I'll post here again if I figure it out.

**Comment by revereche** [comment]
I could have sworn it wasn't working, but apparently first vertex and last vertex both work, though base color doesn't. I guess that's what I get for testing with a color so close to black, using bright blue now and it's obvious. I must have run into this problem because I was using multiple materials on one model, and because the script makes the colors you use so much darker.

Thank you for the help!!
